- name: Remove nginx on the nodes
  hosts: all
  become: yes

  tasks:
    - name: nginx for CentOS
      include_tasks: CentOS_remo.yml
      when: ansible_distribution == 'CentOS'
    
    - name: nginx for Ubuntu
      include_tasks: Ubuntu_remo.yml
      when: ansible_distribution == 'Ubuntu'
